name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.0'

      - name: Install npm
        run: npm install -g npm@7

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXTAUTH_URL: 'http://localhost:3000'

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{secrets.DIR}}
            git stash
            git pull origin master
            npm install 
            npm run build
            cp .env ./dist
            echo "NEXTAUTH_URL=http://localhost:3000" > ./dist/.env
            echo "NEXT_AUTH_SECRET=${{ secrets.NEXT_AUTH_SECRET }}" >> ./dist/.env
            echo "JWT_PASSWORD=${{ secrets.JWT_PASSWORD }}" >> ./dist/.env
            pm2 restart file
